export const reslist = [
  {
    id: 1,
    name: "Terrykitchens",
    deliveryTime: 50,
    costForTwo: 40000,
    cuisine: ["Biriyani,Chicken-tost,avdoSalad"],
    image: "https://assets.vogue.in/photos/61d84b5b9db8964401d2b0e4/4:3/w_4095,h_3071,c_limit/15%20best%20multi-cuisine%20restaurants%20in%20Mumbai,%20New%20Delhi,%20Bengaluru,%20Kolkata%20and%20Goa.jpg",
    avgRating: "4.8",
  },
  {
    id: 2,
    name: "Veer Di Hatti",
    deliveryTime: 20,
    costForTwo: 40000,
    cuisine: ["Angolan ,cuisine Cameroonian,  Chadian, "],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdmLXLfRUiLX8dB9iheveHfGBBvo8qs9nrYw&usqp=CAU",
    avgRating: "4.1",
  },
  {
    id: 3,
    name: "Hilton Inn",
    deliveryTime: 30,
    costForTwo: 40000,
    cuisine: ["Tameroonian,  Chadian, ongolese , Centrafrican"],
    image: "https://imgstaticcontent.lbb.in/lbbnew/wp-content/uploads/2017/07/20105739/19072017_Bengamese_01.jpg",
    avgRating: "3.5",
  },
  {
    id: 4,
    name: "SayaJi",
    deliveryTime: 40,
    costForTwo: 40000,
    cuisine: ["Chadian, ongolese , Centrafrican,Biriyani,Chicken-tost,avdoSalad"],
    image: "https://theroamingfork.com/wp-content/uploads/2022/10/Asian-Noodles.jpg",
    avgRating: "4.9",
  },
  {
    id: 5,
    name: "Indori Zayaka",
    deliveryTime: 60,
    costForTwo: 40000,
    cuisine: ["Centrafrican,Biriyani,Chicken-tost,avdoSalad"],
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRdmLXLfRUiLX8dB9iheveHfGBBvo8qs9nrYw&usqp=CAU",
    avgRating: "3.8",
  },
  {
    id: 6,
    name: "Kate Foods",
    deliveryTime: 45,
    costForTwo: 40000,
    cuisine: ["Chadian,entrafrican,Biriyani,Chicken-tost,avdoSalad"],
    image: "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2018/1/23/0/FN_healthy-fast-food-red-robin-avocado-cobb-salad_s4x3.jpg.rend.hgtvcom.616.462.suffix/1516723515457.jpeg",
    avgRating: "2.8",
  },
  {
    id: 7,
    name: "Shree Gurukripa",
    deliveryTime: 10,
    costForTwo: 40000,
    cuisine: ["Chadian, ongolese , Centrafrican,Biriyani,Chicken-tost,avdoSalad"],
    image: "https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/tfklvouofha0gaw5ieo4",
    avgRating: "3.8",
  },
]

